#logging:
#    pattern:
#        console= "%d _ %msg%n"
##    path: /log/
#    file: /log/wsellLog.log
#    level: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell